### ISSUE TITLE
Debug error with esm-loader-typescript

### ISSUE THREAD

**Issue by abendigo** [brev/esm-loaders#2]
I followed the instructions here: https://github.com/brev/esm-loaders/tree/main/packages/esm-loader-typescript#readme

After running `NODE_OPTIONS="--loader esm-loader-typescript" node index.ts` I get the following error:

    Error: Debug Failure.
    at /home/marko/dev/trial/node_modules/typescript/lib/typescript.js:20138:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (/home/marko/dev/trial/node_modules/typescript/lib/typescript.js:20138:21)
    at Object.createCompilerDiagnostic (/home/marko/dev/trial/node_modules/typescript/lib/typescript.js:20252:20)
    at tryReadFile (/home/marko/dev/trial/node_modules/typescript/lib/typescript.js:41759:40)
    at Object.readConfigFile (/home/marko/dev/trial/node_modules/typescript/lib/typescript.js:41724:32)
    at transform (file:///home/marko/dev/trial/node_modules/esm-loader-typescript/dist/index.js:43:35)
    at transformSource (file:///home/marko/dev/trial/node_modules/create-esm-loader/lib/create-loader.js:80:24)
    at file:///home/marko/dev/trial/node_modules/create-esm-loader/lib/create-loader.js:136:26
    at async file:///home/marko/dev/trial/node_modules/create-esm-loader/lib/create-loader.js:236:7

    Node.js v18.0.0

**Comment by brev** [comment]
Hi @abendigo, thanks for the feedback. Could you happen to post `index.ts` and your `tsconfig.json` so I could try to reproduce? thanks!

**Comment by abendigo** [comment]
It's been a while.. I'll see if I can find the code back.

**Comment by brev** [comment]
Please re-open if/when you can reproduce, thanks!
